### PR TITLE
add to_numeric function

### PR DESCRIPTION
**Pull request by GuanshuTao**
- practice to do on a branch 
- not sure if doing it right, please review

### CODE REVIEW

**Comment by jaymegordo** [comment]
@GuanshuTao everything looks good here, only note is that from now on we'll use new "feature" branches for each new feature instead of a single "user" branch, (my bad  for initially showing it that way)

**Comment by GuanshuTao** [comment]
@jaymegordo Oh I see, so can I change the branch name, or do I need to delete this and create a new branch?

**Review by jaymegordo — CHANGES_REQUESTED** [review]
@GuanshuTao I think we should change the return type to float to be safer

**Comment by jaymegordo** [comment]
@GuanshuTao I changed that one line for you!

**Review by jaymegordo — APPROVED** [review]

**Pull request merged**
